default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: saleschart_development
  pool: 20
  username: root
  password:

test:
  <<: *default
  database: saleschart_development
  pool: 50
  username: root
  password:

production:
  <<: *default
  database: mmp_production
  username: mmp_admin
  password: <%= ENV['MMP_DATABASE_PASSWORD'] %>
  host: <%= ENV['MMP_DATABASE_HOST'] %>
  port: <%= ENV['MMP_DATABASE_PORT'] %>