default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: saleschart_development
  pool: 20
  username: root
  password:

test:
  <<: *default
  database: saleschart_development
  pool: 50
  username: root
  password:

production:
  <<: *default
  database: mmp_production
  username: root
  password: root
